disabled_rules:
  - trailing_whitespace
  - vertical_parameter_alignment
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_end_indentation

included:
  - ios/NearMe

excluded:
  - ios/NearMe/Generated
  - ios/NearMe/Resources
  - ios/_archive

line_length:
  warning: 120
  error: 160

file_length:
  warning: 600
  error: 1200

function_body_length:
  warning: 80
  error: 120

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  min_length: 2
  excluded: [id, x, y, i, j]

reporter: "xcode"
