name: iOS CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'NearMe/**', 'NearMe.xcodeproj/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'NearMe/**', 'NearMe.xcodeproj/**' ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Cache derived data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
    
    - name: Build iOS app
      run: |
        xcodebuild -project NearMe.xcodeproj \
          -scheme NearMe \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          build
    
    - name: Run iOS tests
      run: |
        xcodebuild -project NearMe.xcodeproj \
          -scheme NearMe \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          test
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ios-test-results
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult